### ISSUE TITLE
Build fails in cmake phase

### ISSUE THREAD

**Issue by vbargsten** [rock-drivers/drivers-vicon#2]
The error is:
```
    CMake Error at DataStream/ViconDataStreamSDK_CPP/CMakeLists.txt:20 (install):
      install TARGETS given no LIBRARY DESTINATION for shared library target
      "ViconDataStreamSDK_CPP".
      
```
@skasperski

**Comment by vbargsten** [comment]
The build succeeds without this line:
https://github.com/rock-drivers/drivers-vicon/blob/44073be8381ac5c434f7fe1a44868a7be0b2ef30/DataStream/ViconDataStreamSDK_CPP/CMakeLists.txt#L20

**Comment by skasperski** [comment]
On what kind of system are you building (OS & CMake version)? Is it a rock-workspace?

**Comment by vbargsten** [comment]
ubuntu 18.04; cmake 3.10.2; yes, in rock workspace.

I fixed the issue here by adding the lib install destination: https://github.com/rock-drivers/drivers-vicon/compare/master...vbargsten:drivers-vicon:master

**Comment by skasperski** [comment]
That is kind of a workaround. According to CMake-Docs this should not be necessary.
> For regular executables, static libraries and shared libraries, the DESTINATION argument is not required. For these target types, when DESTINATION is omitted, a default destination will be taken from the appropriate variable from [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs), or set to a built-in default value if that variable is not defined.

Probably this old version of CMake doesn't know this. Ubuntu 18 is somewhat outdated.

**Comment by vbargsten** [comment]
The CMakeLists.txt should include gnuinstalldirs and use the appropriate directory definitions.

**Comment by skasperski** [comment]
Please update and try again.

**Comment by vbargsten** [comment]
Seems to work. Thanks.
